# HealthBar Configuration
format: "&f%damager - &c[%health&c]"
health-format:
  health-used: "&c|"
  health-not-used: "&4|"

gamemode-settings:
  enable-gamemode-settings: true
  disabled-gamemodes:
  - adventure
  - creative

disabled-worlds:
- my_world_name

disabled-entities:
- ender_dragon
- wither

announce-update: true
enable-permission: false


display-names:
  #zombie: "Brain Chopper"
  #skeleton: "King of Archery"